### ISSUE TITLE
Uso de JQuery en widget

### ISSUE THREAD

**Issue by anmaro13** [anmaro13/WebAppBuilder-Widgets#1]
@hhkaos 
Hola Raul, necesito ayuda con Jquery en el widget "SeguroJquery", a pesar de que incluí el plugin me lo sigue sin reconocer.

Gracias!

**Comment by hhkaos** [comment]
Le echamos un ojo luego a la tarde, vale? Y aprovechamos para intentar publicar una app [como esta](https://github.com/mapillary/Mapillary-WebAppWidget/tree/gh-pages)

Creo que el repositorio deberías renombrarlo, tipo WebAppBuilder-Widgets, sino puede dar lugar a pensar que lo que contiene el repositorio es el propio WebAppBuilder.

Abrazo!

**Comment by anmaro13** [comment]
perfect!, la voy ojeando :)
